name: dev

services:
  mariadb:
    image: mariadb:11.8
    container_name: ${MARIADB_HOST}
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DB}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - dev_network

volumes:
  mariadb_data:

networks:
  dev_network:
    name: dev_network
