name: dev

services:
  app:
    image: monica:4.1.2-apache
    container_name: monica
    ports:
      - 9001:80
    environment:
      - APP_KEY=${MONICA_APP_KEY}
      - DB_HOST=${MONICA_DB_HOST}
      - DB_USERNAME=${MONICA_DB_USER}
      - DB_PASSWORD=${MONICA_DB_PASSWORD}
    volumes:
      - monica_data:/var/www/html/storage
    networks:
      - dev_network
    restart: always

volumes:
  monica_data:

networks:
  dev_network:
    name: dev_network